"use client";

import * as React from "react";
import { useState } from "react";
import { ListeningMaterial, GeneratedTrack, GeneratedChooseResponse, AccentTag } from "@/types/listening.types";
import { ListeningAudioRunner } from "./ListeningAudioRunner";
import { ChooseResponseRunner } from "./ChooseResponseRunner";
import { ListeningResults } from "./ListeningResults";
import { saveListeningSession } from "@/actions/listening.actions";
import { NotepadPanel } from "./NotepadPanel";
import { toast } from "sonner";
import { useRouter } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

interface ListeningExamProps {
  material: ListeningMaterial;
  userId?: string;
  mode: "practice" | "simulacro";
}

export function ListeningExam({ material, userId, mode }: ListeningExamProps) {
  const router = useRouter();
  const [examState, setExamState] = useState<"running" | "finished">("running");
  const [scoreInfo, setScoreInfo] = useState<{ totalScore: number; maxScore: number; answers: any } | null>(null);

  const handleFinish = async (answers: Record<string, string>) => {
    // Calculate score
    let pointsEarned = 0;
    const maxScore = material.type === "response" ? 1 : material.questions?.length || 0;

    if (material.type === "response") {
      // It's a choose response, so there is only one question essentially
      // Let's assume the question correct answer is stored in the transcript or questions array
      // For choose_response generated by our prompt, correct answer is usually an option
      const correctAnswer = material.questions?.[0]?.correctAnswer;
      if (answers["0"] === correctAnswer || answers["choose"] === correctAnswer) {
        pointsEarned = 1;
      }
    } else {
      material.questions?.forEach((q, idx) => {
        if (answers[idx.toString()] === q.correctAnswer) {
          pointsEarned += 1;
        }
      });
    }

    setScoreInfo({ totalScore: pointsEarned, maxScore, answers });
    setExamState("finished");

    // Save to DB
    const attempts = material.questions?.map((q, idx) => ({
      questionId: q.id || idx.toString(),
      questionType: q.type || "multiple_choice",
      userAnswer: answers[idx.toString()] || answers["choose"],
      isCorrect: (answers[idx.toString()] || answers["choose"]) === q.correctAnswer,
      timeSpentSeconds: 0 // Track actual time if needed
    })) || [];

    const res = await saveListeningSession(pointsEarned, maxScore, 0, attempts, material.id);
    if (!res.success && userId) {
      toast.error(res.error || "Failed to save session scores.");
    }
  };

  const renderRunner = () => {
    if (material.type === "response") {
      const chooseItem: GeneratedChooseResponse = {
        audio_prompt_text: material.transcript || "",
        options: material.questions?.[0]?.options || [],
        correct_option: material.questions?.[0]?.correctAnswer || "",
        explanation: material.questions?.[0]?.explanation || "",
        accent_tag: material.accent as AccentTag || "en-US",
      };

      return (
        <ChooseResponseRunner
          item={chooseItem}
          mode={mode === "simulacro" ? "mock" : "practice"}
          accent={material.accent as AccentTag || "Random"}
          onAnswer={(ans) => handleFinish({ "choose": ans })}
        />
      );
    }

    const audioTrack: GeneratedTrack = {
      transcript: material.transcript || "",
      questions: material.questions?.map(q => ({
        text: q.text || (q as any).question || "",
        type: q.type,
        options: q.options,
        correctAnswer: q.correctAnswer,
        explanation: q.explanation,
      })) || [],
    };

    return (
      <ListeningAudioRunner
        track={audioTrack}
        mode={mode === "simulacro" ? "mock" : "practice"}
        accent={material.accent as AccentTag || "Random"}
        title={material.title}
        onComplete={handleFinish}
      />
    );
  };

  if (examState === "finished" && scoreInfo) {
    return (
      <ListeningResults 
        score={scoreInfo.totalScore} 
        maxScore={scoreInfo.maxScore} 
        answers={scoreInfo.answers} 
        transcript={material.transcript}
        onExit={() => router.push("/dashboard/practice?tab=listening")} 
      />
    );
  }

  return (
    <div className="w-full relative pb-20 mt-4 max-w-6xl mx-auto px-4">
      <div className="mb-6 flex justify-between items-center bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm">
        <div className="flex items-center space-x-4">
           <Button variant="ghost" size="icon" onClick={() => router.push("/dashboard/practice?tab=listening")} className="rounded-full">
             <ArrowLeft className="w-5 h-5" />
           </Button>
           <div>
             <h1 className="text-xl font-bold bg-gradient-to-r from-slate-900 to-slate-600 dark:from-slate-100 dark:to-slate-400 bg-clip-text text-transparent">
               {material.title}
             </h1>
             <p className="text-sm text-slate-500 font-medium capitalize flex items-center gap-2">
               {material.type} Practice
               <span className="px-2 py-0.5 rounded-full bg-slate-100 dark:bg-slate-800 text-xs">
                 {mode === "simulacro" ? "Exam Mode" : "Practice Mode"}
               </span>
             </p>
           </div>
        </div>
      </div>
      
      {renderRunner()}

      <NotepadPanel />
    </div>
  );
}
