"use client";

import React, { useState, useCallback, useRef, useEffect } from "react";
import {
  MessageSquare,
  ArrowLeft,
  Send,
  Loader2,
  Clock,
  User,
  GraduationCap,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { useRouter } from "next/navigation";
import WritingEditor from "./WritingEditor";
import WritingFeedback from "./WritingFeedback";
import { saveWritingSession } from "@/actions/writing.actions";
import type {
  AcademicDiscussionEvaluation,
  AcademicDiscussionScenario,
} from "@/types/writing.types";

/** Sample scenario (in production, generated by AI or from DB) */
const SAMPLE_SCENARIO: AcademicDiscussionScenario = {
  professorPost:
    "In recent years, many universities have shifted toward online learning platforms. While some argue that this improves access to education and flexibility for students, others contend that it diminishes the quality of academic engagement and social interaction that are essential to the college experience.",
  professorQuestion:
    "Do you believe that online learning can fully replace traditional classroom instruction? Why or why not? Support your argument with reasons and examples.",
  studentPosts: [
    {
      name: "Alice",
      text: "I think online learning is a great supplement to traditional education, but it can't fully replace it. Many subjects, like lab sciences, require hands-on experience. Also, students benefit from face-to-face interactions with professors and peers, which help develop critical thinking and communication skills.",
    },
    {
      name: "Brian",
      text: "I disagree. With advances in technology, virtual labs and video conferencing can replicate most classroom experiences. Online learning also allows students from rural areas to access top universities without relocating. The flexibility it offers is especially important for working students.",
    },
  ],
};

interface AcademicDiscussionProps {
  initialScenario?: AcademicDiscussionScenario;
}

/**
 * Academic Discussion Runner — professor post, student posts, and user editor.
 */
export default function AcademicDiscussion({ initialScenario }: AcademicDiscussionProps) {
  const router = useRouter();
  const scenario = initialScenario || SAMPLE_SCENARIO;
  const [responseText, setResponseText] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [evaluation, setEvaluation] =
    useState<AcademicDiscussionEvaluation | null>(null);
  const [isSaving, setIsSaving] = useState(false);

  // Timer
  const [elapsedSeconds, setElapsedSeconds] = useState(0);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    timerRef.current = setInterval(() => {
      setElapsedSeconds((s) => s + 1);
    }, 1000);
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, []);

  const stopTimer = useCallback(() => {
    if (timerRef.current) clearInterval(timerRef.current);
  }, []);

  const formatTime = (secs: number) => {
    const m = Math.floor(secs / 60);
    const s = secs % 60;
    return `${m}:${s.toString().padStart(2, "0")}`;
  };

  const handleSubmit = useCallback(async () => {
    if (!responseText.trim()) return;
    stopTimer();
    setIsSubmitting(true);

    try {
      const res = await fetch("/api/ai/evaluate-writing-discussion", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          studentResponse: responseText,
          professorPost: scenario.professorPost,
          professorQuestion: scenario.professorQuestion,
          studentPosts: scenario.studentPosts,
        }),
      });
      const data = await res.json();
      if (data.success) {
        setEvaluation(data.evaluation);
        localStorage.removeItem("writing_draft_discussion");
      }
    } catch (err) {
      console.error("Discussion evaluation error:", err);
    }
    setIsSubmitting(false);
  }, [responseText, stopTimer]);

  const handleSaveAndReturn = useCallback(async () => {
    setIsSaving(true);
    await saveWritingSession({
      taskType: "academic_discussion",
      score: evaluation?.score_0_5 || 0,
      maxScore: 5,
      timeSpentSeconds: elapsedSeconds,
      details: {
        responseText,
        scenario,
        evaluation,
      },
    });
    setIsSaving(false);
    router.push("/practice/writing");
  }, [evaluation, elapsedSeconds, responseText, router]);

  // ── EVALUATION RESULTS ──
  if (evaluation) {
    return (
      <div className="max-w-4xl mx-auto space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
        <WritingFeedback
          type="academic_discussion"
          result={evaluation}
          userText={responseText}
        />
        <button
          onClick={handleSaveAndReturn}
          disabled={isSaving}
          className={cn(
            "w-full py-3.5 rounded-xl font-semibold text-sm",
            "bg-cyan-500/10 border border-cyan-500/20 text-cyan-300",
            "hover:bg-cyan-500/20 flex items-center justify-center gap-2 transition-all"
          )}
        >
          {isSaving ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" /> Saving…
            </>
          ) : (
            <>
              Save & Return <ArrowLeft className="w-4 h-4" />
            </>
          )}
        </button>
      </div>
    );
  }

  // ── WRITING SCREEN ──
  return (
    <div className="max-w-5xl mx-auto space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      {/* Top bar */}
      <div className="flex items-center justify-between">
        <button
          onClick={() => router.push("/practice/writing")}
          className="text-gray-400 hover:text-white transition-colors flex items-center gap-2 text-sm"
        >
          <ArrowLeft className="w-4 h-4" /> Back
        </button>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-gray-800 border border-gray-700 text-sm text-gray-400">
            <Clock className="w-3.5 h-3.5" />
            {formatTime(elapsedSeconds)}
          </div>
        </div>
      </div>

      {/* Discussion Thread */}
      <div className="bg-gray-900/80 rounded-2xl border border-gray-700/50 overflow-hidden">
        {/* Header */}
        <div className="bg-cyan-500/5 border-b border-gray-700/50 px-6 py-4">
          <div className="flex items-center gap-2 mb-1">
            <MessageSquare className="w-4 h-4 text-cyan-400" />
            <h3 className="text-base font-bold text-white">
              Academic Discussion Forum
            </h3>
          </div>
          <p className="text-xs text-gray-500">
            Read the discussion and contribute your response
          </p>
        </div>

        {/* Professor post */}
        <div className="p-6 border-b border-gray-800">
          <div className="flex items-start gap-3">
            <div className="w-10 h-10 rounded-full bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center shrink-0 shadow-lg shadow-cyan-500/10">
              <GraduationCap className="w-5 h-5 text-white" />
            </div>
            <div className="flex-grow">
              <div className="flex items-center gap-2 mb-1">
                <span className="text-sm font-bold text-white">
                  Professor
                </span>
                <span className="text-xs px-2 py-0.5 rounded bg-cyan-500/15 text-cyan-300 border border-cyan-500/20">
                  Instructor
                </span>
              </div>
              <p className="text-sm text-gray-300 leading-relaxed mb-3">
                {scenario.professorPost}
              </p>
              <div className="bg-cyan-500/5 border border-cyan-500/15 rounded-xl p-3">
                <p className="text-sm text-cyan-200 font-medium">
                  {scenario.professorQuestion}
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Student posts */}
        {scenario.studentPosts.map((student, idx) => (
          <div
            key={idx}
            className={cn(
              "p-6",
              idx < scenario.studentPosts.length - 1 &&
                "border-b border-gray-800"
            )}
          >
            <div className="flex items-start gap-3">
              <div
                className={cn(
                  "w-10 h-10 rounded-full flex items-center justify-center shrink-0",
                  idx === 0
                    ? "bg-gradient-to-br from-purple-500 to-pink-600"
                    : "bg-gradient-to-br from-orange-500 to-amber-600"
                )}
              >
                <User className="w-5 h-5 text-white" />
              </div>
              <div className="flex-grow">
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-sm font-bold text-white">
                    {student.name}
                  </span>
                  <span className="text-xs text-gray-600">Student</span>
                </div>
                <p className="text-sm text-gray-300 leading-relaxed">
                  {student.text}
                </p>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Engagement note */}
      <div className="bg-amber-500/5 border border-amber-500/15 rounded-xl p-3 flex items-start gap-2">
        <MessageSquare className="w-4 h-4 text-amber-400 mt-0.5 shrink-0" />
        <p className="text-xs text-amber-300/80 leading-relaxed">
          <span className="font-semibold">Tip:</span> Engage with the ideas of
          {scenario.studentPosts.map(s => ` ${s.name}`).join(' and')} in your response. Reference their arguments, agree
          or disagree, and add your own perspective with examples.
        </p>
      </div>

      {/* Editor */}
      <WritingEditor
        value={responseText}
        onChange={setResponseText}
        placeholder="I'd like to add to this discussion. In my view..."
        draftKey="discussion"
        minHeight={200}
      />

      {/* Submit button */}
      <button
        onClick={handleSubmit}
        disabled={!responseText.trim() || isSubmitting}
        className={cn(
          "w-full py-3.5 rounded-xl font-semibold text-sm transition-all flex items-center justify-center gap-2",
          responseText.trim()
            ? "bg-cyan-500/15 border border-cyan-500/30 text-cyan-300 hover:bg-cyan-500/25"
            : "bg-gray-800 border border-gray-700 text-gray-500 cursor-not-allowed"
        )}
      >
        {isSubmitting ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" /> Evaluating with AI…
          </>
        ) : (
          <>
            <Send className="w-4 h-4" /> Submit Response
          </>
        )}
      </button>
    </div>
  );
}
